### ISSUE TITLE
Prevent pool token deposits when reward rate is zero

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/web3-smart-contracts#61]
What will happen if the LP rewards smart contract will no longer be funded? Assuming that we will not be funding it forever, should we implement a way to prevent liquidity providers from depositing pool tokens if the liquidity rewards program has ended?

---

Depends on #42

**Comment by hhio618** [comment]
@nya-elimuai  My suggestion is to add a method to pause the contract whenever the reward program is over. 
Also, there is another case when the amount of an account claim is bigger than the remaining rewards on the contract. This case exists because our calculation is an estimation of the actual rewards needed.

**Comment by nya-elimuai** [comment]
@hhio618 Yes, that sounds like a workable solution. Also, we could simply set the reward emission rate to 0.0 to indicate the end of the program, and add a check for zero before running the `depositPoolTokens()` function? Which of these two options do you think would require the least amount of code?

**Comment by hhio618** [comment]
@nya-elimuai Setting rewardRate to 0.0 is more suitable here :+1: This way we stop rewarding more $ELIMU to current lp users and prevent new deposits to the contract.
